# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Services Unit Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-dir: [./src]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ${{ matrix.working-dir }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock pytest-cov absl-py pygerrit2
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      working-directory: ${{ matrix.working-dir }}
      run: |
        pytest --cov=./ --cov-report=xml
    - name: "Codecov Coverage & Upload"
      uses: codecov/codecov-action@v1
      with:
          files: src/coverage.xml
          flags: unittests
          path_to_write_report: ./coverage/codecov_report.txt
          verbose: true
          fail_ci_if_error: false
