# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Services Unit Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working-dir: [./src]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      working-directory: ${{ matrix.working-dir }}
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-mock
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      working-directory: ${{ matrix.working-dir }}
      run: |
        python -m pytest